# Generated by Django 3.0.3 on 2020-08-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mMsg', models.CharField(max_length=100)),
                ('mFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='register.user')),
                ('mTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='register.user')),
            ],
        ),
    ]
