# Generated by Django 3.0.3 on 2020-08-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatarea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.AddField(
            model_name='chat',
            name='mTime',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
    ]
