# Generated by Django 3.0.3 on 2020-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatarea', '0002_auto_20200815_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='mTime',
        ),
        migrations.AddField(
            model_name='chat',
            name='id',
            field=models.AutoField(auto_created=True, default=2020, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
