# Generated by Django 3.0.3 on 2020-08-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatarea', '0003_auto_20200815_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
