# Generated by Django 3.0.3 on 2020-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatarea', '0005_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
