# Generated by Django 3.0.3 on 2020-08-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatarea', '0006_chat_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='mMsg',
            new_name='mReceived',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='chat',
            name='mSent',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
