# Generated by Django 3.0.3 on 2020-08-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('mName', models.CharField(max_length=20)),
                ('mEmail', models.CharField(max_length=30)),
                ('mUsername', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mPassword', models.CharField(max_length=25)),
            ],
        ),
    ]
