# Generated by Django 3.0.3 on 2020-09-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200905_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mImage',
            field=models.TextField(default='static/register/images/user.png'),
        ),
    ]
