# Generated by Django 3.0.3 on 2020-08-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mReceived', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='register.user')),
                ('mSent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='register.user')),
            ],
        ),
    ]
