# Generated by Django 3.0.3 on 2020-08-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='mFriendUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriend', to='register.user'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='mUsername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='register.user'),
        ),
    ]
