# Generated by Django 3.0.3 on 2020-09-12 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200905_1537'),
        ('home', '0002_auto_20200816_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mLikes', models.IntegerField(default=0, max_length=5)),
                ('mCaption', models.CharField(default='', max_length=199)),
                ('mPhoto', models.TextField(default=None)),
                ('mUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
        ),
    ]
