# Generated by Django 3.0.3 on 2020-09-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='mLikes',
            field=models.IntegerField(default=0),
        ),
    ]
